### PR TITLE
Fix arc draw

### PR DESCRIPTION
**Pull request by xubury**
As this comment says: https://github.com/JamesBremner/DXF_Viewer/pull/17#issuecomment-597509374
I am having trouble building windex viewer, so I didn't tested it for windex viewer.

### CODE REVIEW

**Comment by xubury** [comment]
commit: https://github.com/JamesBremner/DXF_Viewer/pull/22/commits/b916aeb391afa911eecd21aa0c188e4814c7c880 fix this issue: https://github.com/JamesBremner/DXF_Viewer/issues/16

**Comment by JamesBremner** [comment]
This pull requests breaks the windex build.

Note that the problems with arc drawing in the wxWidgets build are fixed in d8ab4913915cb63ebab4f86440f4b1bca02dbd8b

( If you have problems with the windex build, open an issue and describe them.  The windex build is the only build fully supported - means that I will not be adding any features to the other builds.  )

**Comment by xubury** [comment]
ok, that will work too. You may also need to correct the doc for getDraw in Arc.h.

**Comment by JamesBremner** [comment]
Done

**Pull request closed without merging**
